name: hestia_navigation 
description: Hestia Navigation libraries for Dart on the server and flutter
author: Hestia Authors <chonebz@gmail.com>
homepage: https://github.com/hestia-io/hestia-dart
version: 0.3.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  grpc: ^2.1.2
  async: ^2.3.0
  protobuf: ^0.14.1
  hestia_core: ^0.2.0

dev_dependencies:
  test: ^1.6.9

